### ISSUE TITLE
GVExport causes a blank screen

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#294] opened 2022-12-07 13:09 UTC
The module GVExport causes a blank screen. See
https://www.webtrees.net/index.php/en/forum/help-for-release-2-1-x/37515-php-8-blank-pages-problem-with-module#96073

But there is not enough information available. I'm using GVExport with webtrees 2.1.12 without any problems.

**Comment by Neriderc** [comment] 2022-12-07 20:41
Thanks for bringing this to my attention. It looks to have been resolved by updating to the latest version.

Probably there was some weird state caused by switching PHP versions or by using an older GVExport version with a newer webtrees version. I have been using PHP8 right through development with no issues.

I'll close this but I am keen to hear when these issues are raised. Is there a way to get notified on the forum when a keyword is mentioned?

**Closed by Neriderc** 2022-12-07 20:41 UTC
