### ISSUE TITLE
Bug in 2.1.20 abbreviation area

### ISSUE THREAD

**Issue by marwelin** [Neriderc/GVExport#477] opened 2024-03-25 06:17 UTC
Overall, GVExport 2.1.20 works smotth together with webtrees 2.1.19, except of this issue I noticed.
- When changing "Appearance > Abbreviations > Abbreviated Names" to "Given name initials and surname" GVExport does not work any more.
- The error message is "Login expired. Reloading page..."
- "Abbreviated Names" cannot be set to another value any more. GVExport must be deinstalled and the setup data must be deleted.

**Comment by Neriderc** [comment] 2024-03-25 08:43
I haven't managed to reproduce this, these settings work fine for me. I had a look back through the code changes and there's nothing major that could cause this (no database or browser storage changes), so I'm not sure what the issue could be.

Since you mention deleting the setup data, I presume this means you aren't able to trigger the issue again? It would have been helpful to know the error in the browser console.

I'll leave this open in the hope someone else has the same issue. **If you're reading this and you have had this issue**, before re-installing could you try the following things:

First, right click on the page and choose "Inspect", then in the panel that opens, choose "Console". Look for anything in red, and reply here with the error message it shows (a screen shot would be great). Note that not all errors come from GVExport (often they are from browser plugins), but it's a good starting point.

Additionally, if refreshing the page doesn't resolve the issue, it would be good to know if Shift+Refresh helps, or if opening in a private window helps (called InPrivate in Edge, Incognito in Chrome, Private window in Firefox - accessed from the menu at the top right of the browser with three dots or lines). These things are all subtly different and help to narrow down the source of the problem.

**Comment by marwelin** [comment] 2024-03-25 11:58
It's incredible. I tried to repoduce it doing the same steps (I remember to), but I cannot reproduce it. Sorry.
If it comes up again, I will do the steps you described above.

**Comment by Neriderc** [comment] 2024-04-04 23:40
There don't seem to be any other reports of this happening so I'll close this issue. It can be reopened in future if it comes up again.

**Closed by Neriderc** 2024-04-04 23:40 UTC
