### ISSUE TITLE
save options to file results in endless loop of triggers to update the browser render.

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#301] opened 2022-12-11 07:24 UTC
After downloading the options file there is a fast endless loop of browser updates.

**Comment by Neriderc** [comment] 2022-12-11 07:45
Any more info? It runs fine for me, have tested in Firefox and Chrome.

Are there any javascript errors in the console?

**Comment by hartenthaler** [comment] 2022-12-11 08:58
It happens in my production system and in my test system. It happens when using Edge and Firefox.

You can see it at http://ahnentest.hartenthaler.eu/index.php?route=%2Fmodule%2F_GVExport_%2FChart%2Fassess&xref=I132#

If there is only one person in the diagram the loop stops after 5 refreshes. My first test was with 238 persons, so maybe "endless" means maybe 1000 iterations.

No related error in the development console.

**Comment by Neriderc** [comment] 2022-12-11 09:10
Thanks! I'll take a look at this when I get a chance, hopefully tomorrow.

I do see it happening on your site so hopefully I can replicate it for myself.

**Comment by Neriderc** [comment] 2022-12-11 09:15
I just had a quick look in the code, I have put a closing } in the wrong place. I'm on mobile now but will fix it up tomorrow.

**Comment by hartenthaler** [comment] 2022-12-11 09:16
That was as fast as always! Thanks!

**Closed** 2022-12-11 19:32 UTC

**Comment by Neriderc** [comment] 2022-12-11 19:49
All done. Let me know if you still have issues, but I'm pretty confident this was the cause.

**Comment by hartenthaler** [comment] 2022-12-11 22:05
Now it is ok! Thank you!

**Comment by schuco** [comment] 2022-12-12 09:58
I have tried, it works fine!
Thank you!!
