### ISSUE TITLE
Download of png and jpg not possible if Graphviz is not installed at server

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#280] opened 2022-11-20 17:24 UTC
Download of pdf is ok, but not png or jpg.

```
Error (return code 127) executing command " -Tpng -o/tmp/c4ca4238a0b923820dcc509a6f75849b/gvexport.png /tmp/c4ca4238a0b923820dcc509a6f75849b/gvexport.dot" in "/mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees".
Graphviz error:
sh: -Tpng: command not found
```

**Comment by Neriderc** [comment] 2022-11-20 18:50
Hmm I don't see this error, it works for me. It's pretty clear it's trying to run GraphVis on the server. Do you see a message under the output file type selection about options being limited? If not then that could be a clue as to where the issue is.

Also do you see any javascript errors in the console? If there are errors this may stop the javascript override kicking in.

**Comment by hartenthaler** [comment] 2022-11-20 20:31
In my productive system and in my test system there is a message "Options are restricted ...". I'm using the latest development version of GVExport.
**Using Edge:**
In my productive system, I was one time successful in downloading a png. Now all downloads of png and jpg are not successful.
In my test system, I can download png, SVG, jpg without any problem (using the same software version), but when trying a pdf download there is no reaction.
I cannot see any errors in the development console of the browser.

**Using Firefox:**
In my test system, I was successful in downloading png and jpg. All downloads of pdf are not successful.
```
Error (return code 127) executing command " -Tpdf -o/tmp/c4ca4238a0b923820dcc509a6f75849b/gvexport.pdf /tmp/c4ca4238a0b923820dcc509a6f75849b/gvexport.dot" in "/mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees".
Graphviz error:

sh: -Tpdf: command not found
```
There is an error message: _Uncaught ReferenceError: jsPDF is not defined_

Maybe I should delete all files and install GVExport again from scratch instead of overwriting the files on the server.

**Comment by Neriderc** [comment] 2022-11-20 20:46
> Maybe I should delete all files and install GVExport again from scratch instead of overwriting the files on the server.

This would be a good idea. I have started to make big changes to structure in some initial small ways. In theory this should not affect it other than having some duplicate files lying around, but please do try a clean install and see if this helps.

It's interesting that jsPDF is not assigned (the library used for generating client-side PDFs) but you've said that PDF download is working! I actually renamed the variable that holds the jsPDF instance (I think it's now called jsPDFinst) because there was a bit of confusion in the code between the instance and the class. Perhaps overwriting files has left a bit of inconsistency here, so try a clean install and hopefully that should help. Let me know how you go! I'll have to remember to make special mention of doing a clean install when releasing the next version, so others are aware.

**Comment by hartenthaler** [comment] 2022-11-20 22:15
Ok, after fresh installation:

On productive system using EDGE: download of DOT and PNG are working, download of SVG, JPG, and PDF results in a similar but different error message (_sh: -Tpdf: command not found_).

On productive system using FIREFOX: download of SVG, DOT and PNG are working, download of PDF results in  _Uncaught ReferenceError: jsPDF is not defined_. Download of JPG results in

> TypeError: NetworkError when attempting to fetch resource. [ahnen:2738:21](https://ahnen.hartenthaler.eu/module/_GVExport_/Chart/ahnen?xref=I43968)
> Successfully compiled asm.js code (total compilation time 602ms) [Asset](https://ahnen.hartenthaler.eu/module/_GVExport_/Asset?asset=javascript%2Ffull.renderer.js&hash=1668981426)
> Diese Seite befindet sich im Kompatibilitätsmodus (Quirks). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>".
> [ahnen](https://ahnen.hartenthaler.eu/module/_GVExport_/Chart/ahnen?xref=I43968)
> Das Cookie "GVEUserDefaults" verfügt über keinen gültigen Wert für das "SameSite"-Attribut. Bald werden Cookies ohne das "SameSite"-Attribut oder mit einem ungültigen Wert dafür als "Lax" behandelt. Dadurch wird das Cookie nicht länger an Kontexte gesendet, die zu einem Drittanbieter gehören. Falls Ihre Anwendung das Cookie in diesen Kontexten benötigt, fügen Sie bitte das Attribut "SameSite=None" zu ihm hinzu. Weitere Informationen zum "SameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite.

On test system using FireFox: all downloads are ok, but pdf results in _Uncaught ReferenceError: jsPDF is not defined_.

**Comment by Neriderc** [comment] 2022-11-20 23:41
Great, thanks for that. When I get a chance I'll test it on my development machine to see if I can reproduce it.

I'm wondering if it load the javascript library, or possibly that it can load it but it's not loading in time. In theory there is protective against this but perhaps it is not working as intended.

Possibly moving to loading it on demand instead of on page load would be good. There are other benefits to this as well so I've always meant to explore this.

It's a little difficult for me to test things that are to do with internet speed. My development instance runs on my laptop so there's no delay, and my production server sits across the room so any delay is very minimal (it goes via my LAN not  the internet unless I'm not connected to my oen wifi). So I will test if I can see the error, and if not I'll try changing when it's loaded to see if it helps you.

**Closed** 2022-11-21 05:37 UTC

**Comment by Neriderc** [comment] 2022-11-21 06:13
Ok this was just a plain mistake on my part. I've had GraphViz installed recently for testing the resizing, so didn't find this issue. I've done a little change to fix this, and merged in some other small changes I was working on while I was at it.

**Comment by hartenthaler** [comment] 2022-11-21 12:53
... now it is working perfectly again! Thanks!

**Comment by Neriderc** [comment] 2022-11-21 18:49
Thanks for finding this issue before it was put into a release 😅

If nothing urgent comes up I think that will be all for this release, but I'm just playing with some automated testing before doing the release. It won't cover everything but I'm hoping it will cover a lot that I don't normally test before each release. I haven't quite worked out how I might test if the downloads are working correctly but if I work it out I'll try to ensure it is picked up if it ever happens again.
