### ISSUE TITLE
When showing multiple marriages, they don't look nice and Links don't work in PDF's files.

### ISSUE THREAD

**Issue by elysch** [Neriderc/GVExport#531] opened 2024-11-19 23:31 UTC
Hi.

I've just saw that when multiple marriages are active, they doesn't look nice in the report: 

![MultipleMarriagesGVExport-20241119](https://github.com/user-attachments/assets/f43fc676-b5dc-44cb-a990-73756f8625f5)

I suggest adding a blank line with a "-" between each one.

Ely.

P.S.: I remember reporting the issue about the links on PDF's but don't see any issue active mentioning it that's why I add it here. (Sorry, don't want to annoy anybody)

**Comment by elysch** [comment] 2024-11-19 23:48
I discovered another thing.

If each marriage has a "first image", only the first one is shown, instead of showing the first image of each marriage.

![image](https://github.com/user-attachments/assets/f5ba85d5-15db-44fc-a6a4-abc98a7bb63e)

Ely

**Comment by Neriderc** [comment] 2024-11-19 23:53
> I've just saw that when multiple marriages are active, they doesn't look nice in the report:

Ah it seems when the first line is too long, it wraps to the next line but doesn't correctly move the second marriage down. 

I'm not sure that the dash is necessary, though. The dash implies some sort of time period, like "John Smith, 1940-1999". I think a space between looks just fine. Thoughts?

![mockup of family record with dash between two marriages](https://github.com/user-attachments/assets/810696e8-92cf-417e-9c42-5e35f045097b)

![mockup of family record without dash](https://github.com/user-attachments/assets/c1595c64-0c84-4668-b5a9-1da6258124e9)

> P.S.: I remember reporting the issue about the links on PDF's but don't see any issue active mentioning it that's why I add it here. (Sorry, don't want to annoy anybody)

Do you have Graphviz installed on the server? This is necessary for links in PDFs, and you can't use functionality that is only available with client-side generation (I think this is just photo shapes).

> If each marriage has a "first image", only the first one is shown, instead of showing the first image of each marriage.

I'll have a look into this and see if I can fix it.

**Comment by elysch** [comment] 2024-11-20 00:12
Wow... really fast answer!!!!

You're right... the dash is not needed at all.

The images I added to the issue come from the generated pdf.

Yes... I have Graphviz installed on sever and is active. 

![image](https://github.com/user-attachments/assets/713f8464-07b1-4def-b1fa-e6a19ad4fd58)

And the "links" setting is active.

![image](https://github.com/user-attachments/assets/b08e0f92-4eeb-469c-9cba-70e00e95ee36)

**Comment by Neriderc** [comment] 2024-11-20 00:56
> Wow... really fast answer!!!!

I happened to be checking my emails when you created this issue :slightly_smiling_face: 

> The links work just fine in the browser, but not in the PDF file

Interesting. The browser links are separate so aren't relevant to the PDF links, but it looks like it should be working. It is definitely working for me. Is this also disabled?
![screenshot of option to change photo shape](https://github.com/user-attachments/assets/1aba06b9-4622-4b17-a26f-a9ecee598fd3)

**Comment by elysch** [comment] 2024-11-20 16:04
I can see a lot of lines like the following in the dot file:

`I57 [ label=<<TABLE COLOR="#606060" BORDER="1" CELLBORDER="0" CELLPADDING="2" CELLSPACING="0" BGCOLOR="#fefefe" TARGET="_blank" HREF="https://...`

Those links work ok when I directly copy them to the browser.

When the individual has an image, the link looks like this (replaced the domain and part of the path with : XXX.XXX.XXX)

HREF="https://XXX.XXX.XXX/media-download?xref=M6&amp;fact_id=f55c3eee5dbf1783852f043e1e577750&amp;disposition=inline&amp;mark=0"

When I copy one of those links to the browser I get a webtrees message saying `The parameter “disposition” is missing.`

**Comment by Neriderc** [comment] 2024-11-20 23:28
I don't think the comment about disposition would be an issue, it's likely because the URL has the & encoded as &amp; but in real use it shouldn't be an issue. In any case, it should at least open something if clicked. 

Here is one I've generated. It's in my dev environment so the link won't actually work, but when you open the PDF and click on a person it should open a browser window and try to go there. Does it work?

[gvexport.pdf](https://github.com/user-attachments/files/17837711/gvexport.pdf)

You do seem to have a slightly older version of Graphviz installed. I'm running webtrees in a docker container, and if I run `dpkg -s graphviz` it tells me the version is `Version: 2.42.2-7+deb12u1`

For some reason I don't understand, if I run `dot -v` then it tells me `dot - graphviz version 2.43.0 (0)` which seems to imply the graphviz version is 2.43.0.

In either case, you're running  2.40.1 so perhaps this difference is the problem? Seems odd though, if it was working before.

**Comment by elysch** [comment] 2024-11-21 01:59
Could you please send to me your .dot file an let me know the dot command parameters I should use?

Just to be sure.

In my pdf not even the mouse pointer changes when you move over a supposed to be link.

**Comment by Neriderc** [comment] 2024-11-21 02:11
Here is my settings file which you should be able to load using the option in GVExport. The people will need to match someone in your tree (so you probably need to update the starting individual) but otherwise it should load ok: 

[gvetest - Settings.json](https://github.com/user-attachments/files/17838791/gvetest.-.Settings.json)

I can't upload the DOT here as it's an unsupported file type but here is the contents:

```
digraph WT_Graph {
ranksep="0.15 equally"
nodesep="0.15"
dpi="72"
mclimit="1"
rankdir="LR"
pagedir="LT"
bgcolor="#eeeeee"
splines="spline"
edge [ style=solid, arrowhead=normal, arrowtail=none];
node [ shape=plaintext font_size="10" fontname="Arial"];
X1 [ label=<<TABLE COLOR="#606060" BORDER="1" CELLBORDER="0" CELLPADDING="2" CELLSPACING="0" BGCOLOR="#fefefe" TARGET="_blank" HREF="http://192.168.1.100:8089/tree/gvetest/individual/X1/Joseph-Joe-BLOGGS"><TR><TD COLSPAN="6" CELLPADDING="2" BGCOLOR="#add8e6" PORT="nam" ></TD></TR><TR><TD ROWSPAN="2" CELLPADDING="1" PORT="pic" WIDTH="40" HEIGHT="40" FIXEDSIZE="true" ALIGN="CENTER" VALIGN="MIDDLE"><IMG SCALE="true" SRC="/var/www/webtrees/app/../data/media/boy5.png" ALT="Joseph Joe BLOGGS"  /></TD><TD ALIGN="LEFT" BALIGN="LEFT"  TARGET="_BLANK" CELLPADDING="4" PORT="dat"><FONT COLOR="#333333" POINT-SIZE="12">Joseph "Joe" BLOGGS</FONT><BR /><FONT COLOR="#555555" POINT-SIZE="10">* 4 May 1944 </FONT><BR /><FONT COLOR="#555555" POINT-SIZE="10">† 7 March 2004 (Place, Death)</FONT> </TD><TD ROWSPAN="2" CELLPADDING="1" PORT="pic" WIDTH="0" HEIGHT="40" FIXEDSIZE="true"></TD><TD ROWSPAN="2" CELLPADDING="1" PORT="pic" WIDTH="0" HEIGHT="40" FIXEDSIZE="true"></TD><TD ROWSPAN="2" CELLPADDING="1" PORT="pic" WIDTH="0" HEIGHT="40" FIXEDSIZE="true"></TD><TD CELLPADDING="10"></TD></TR></TABLE>>];
X40 [ label=<<TABLE COLOR="#606060" BORDER="1" CELLBORDER="0" CELLPADDING="2" CELLSPACING="0" BGCOLOR="#fefefe" TARGET="_blank" HREF="http://192.168.1.100:8089/tree/gvetest/individual/X40/Jane-Smith"><TR><TD COLSPAN="6" CELLPADDING="2" BGCOLOR="#ffb6c1" PORT="nam" ></TD></TR><TR><TD ROWSPAN="2" CELLPADDING="1" PORT="pic" WIDTH="40" HEIGHT="40" FIXEDSIZE="true" ALIGN="CENTER" VALIGN="MIDDLE"><IMG SCALE="true" SRC="/var/www/webtrees/app/../data/media/girl1.png" ALT="Jane Smith"  /></TD><TD ALIGN="LEFT" BALIGN="LEFT"  TARGET="_BLANK" CELLPADDING="4" PORT="dat"><FONT COLOR="#333333" POINT-SIZE="12">Jane Smith</FONT><BR /><FONT COLOR="#555555" POINT-SIZE="10">* 2 August 1945 </FONT>  </TD><TD ROWSPAN="2" CELLPADDING="1" PORT="pic" WIDTH="0" HEIGHT="40" FIXEDSIZE="true"></TD><TD ROWSPAN="2" CELLPADDING="1" PORT="pic" WIDTH="0" HEIGHT="40" FIXEDSIZE="true"></TD><TD ROWSPAN="2" CELLPADDING="1" PORT="pic" WIDTH="0" HEIGHT="40" FIXEDSIZE="true"></TD><TD CELLPADDING="10"></TD></TR></TABLE>>];
X41 [ color="#606060",fillcolor="#ffffee", target="_blank" href="http://192.168.1.100:8089/tree/gvetest/family/X41/Joseph-Joe-BLOGGS-Jane-Smith", target="_blank",  shape=oval, style="filled", margin=0.01, label=<<TABLE border="0" CELLPADDING="5" CELLSPACING="0"><TR><TD><FONT COLOR="#555555" POINT-SIZE="10">∞  16 March 1967<BR /></FONT></TD></TR></TABLE>>];
X1 -> X41 [color="#555555", style="solid", arrowsize=0.3]
X40 -> X41 [color="#555555", style="solid", arrowsize=0.3]
}
```

**Comment by Neriderc** [comment] 2024-11-21 02:18
> Could you please send to me your .dot file an let me know the dot command parameters I should use?

Oh sorry, you're gonna try manually running the command? Running this command works for me, and has the links:

`dot  -Tpdf -o new.pdf gvexport.dot`

But this is done with a different version of Graphviz, on my computer not in the docker container with webtrees:
`dot - graphviz version 9.0.0 (20230911.1827)`

**Comment by elysch** [comment] 2024-11-21 03:24
In the new.pdf links doesn't work.
I don't get it. Something must have changed in the server. But I don't remember changing Graphviz.

Forget it, I'll try to upgrade or do something 

Thank you for your time

**Comment by Neriderc** [comment] 2024-11-21 05:04
Are you familiar with docker? It would be interesting to know if it works for you in a webtrees docker container (which should be system agnostic and therefore work the same everywhere), but it can be a bit of a learning curve if you're not already familiar.

Alternatively, it is probably not too difficult to download a more recent version of Graphviz directly from their site.

**Comment by elysch** [comment] 2024-11-21 16:11
I installed Graphviz CentOS 8 rpm's  and now "dot -V" reports

`dot - graphviz version 2.44.1 (20200629.0846)`

The links are still missing. It's weird. Just in case I looked for any "config" file without success.

Before that, I tried more recent graphviz versions without success, culdn't install them since my server is kind of old.

About containers... I don't have an environment now, but I look for it also :)   (Have you heard about litespeed conteiners?)

**Comment by elysch** [comment] 2024-11-21 16:31
By the way. 

> I'm not sure that the dash is necessary, though. The dash implies some sort of time period, like "John Smith, 1940-1999". I think a space between looks just fine.


Where did you add the needed newline?
Downloaded the last main branch and it still shows the marriages one after the other in the same line.

Tnx

**Comment by elysch** [comment] 2024-11-21 16:54
What I've just found is that if I convert .dot to ps and then convert it using ghostscript's ps2pdf , the links do work.

`dot -Tps2 -o new.ps /tmp/x.dot`

`ps2pdf /tmp/new.ps  /tmp/new2.pdf`

**Comment by Neriderc** [comment] 2024-11-21 21:53
> About containers... I don't have an environment now, but I'll look for it also :) (Have you heard about litespeed conteiners?)

I hadn't, and it sounds like they were only [announced a couple of months ago](https://blog.litespeedtech.com/2024/09/09/introducing-litespeed-containers/). It also sounds like it's designed for people that sell web hosting.

For containers hosting individual services (like webtrees), I think docker is already the defacto solution and it does a good job of it. I'm happy to help if you want some instructions on how to set up webtrees in a docker container.

> P.S. I'm thinking the links never worked in pdf's generated in this server. Maybe I mistakenly just tested them in the browser on this year... The newest GVexport report with working links I have is from 2017 :/ :(

That's really interesting. If you ever work it out it would be good to understand why it isn't working.

> Where did you add the needed newline? Downloaded the last main branch and it still shows the marriages one after the other in the same line.

Sorry, I haven't made this change yet. The screen shot was created by manually editing the DOT file, but I intend to make this change next.

> What I've just found is that if I convert .dot to ps and then convert it using ghostscript's ps2pdf , the links do work, but apparently ghostscript doesn't support utf-8

Hmm that's a shame. I'm reading [here](https://graphviz.org/docs/outputs/pdf/) that your method is the recommended way if your environment doesn't have the Cairo renderer. So that is something to test. Are you able to use the SVG output in GVExport? This specifically calls the Cairo renderer as it is needed for the pictures.

**Comment by elysch** [comment] 2024-11-21 22:42
Thank you for your offering about Dockers... Apparently I don't have enough ram at the moment.

The SVG file, without links option, was generated without a problem. I opened it in chrome browser and seems ok. 

```
[xxxx@xxxx webtrees]# dot -v -Tpdf -o /tmp/new5.pdf /tmp/x.dot
dot - graphviz version 2.44.1 (20200629.0846)
Using render: cairo:cairo
Using device: pdf:cairo:cairo
libdir = "/usr/lib64/graphviz"
Activated plugin library: libgvplugin_dot_layout.so.6
Using layout: dot:dot_layout
The plugin configuration file:
        /usr/lib64/graphviz/config6
                was successfully loaded.
    render      :  cairo dot dot_json fig json json0 map mp pic pov ps svg tk vml xdot xdot_json
    layout      :  circo dot fdp neato nop nop1 nop2 osage patchwork sfdp twopi
    textlayout  :  textlayout
    device      :  bmp canon cmap cmapx cmapx_np dot dot_json eps fig gv ico imap imap_np ismap jpe jpeg jpg json json0 mp pdf pic plain plain-ext png pov ps ps2 svg svgz tif tiff tk vml vmlz x11 xdot xdot1.2 xdot1.4 xdot_json xlib
    loadimage   :  (lib) bmp eps gif ico jpe jpeg jpg pdf png ps svg
pack info:
  mode   undefined
  size   0
  flags  0
  margin 8
pack info:
  mode   node
  size   0
  flags  0
Warning: Illegal attribute ALT in <IMG> - ignored
Warning: No such file or directory while opening /var/www/webtrees/app/../data/media/boy5.png
Error: No or improper image file="/var/www/webtrees/app/../data/media/boy5.png"
fontname: "Arial" resolved to: (PangoCairoFcFont) "Nimbus Sans, Regular" /usr/share/fonts/urw-base35/NimbusSans-Regular.otf
Warning: fixed cell size with unspecified width or height
Warning: fixed cell size with unspecified width or height
Warning: fixed cell size with unspecified width or height
network simplex:  4 nodes 4 edges maxiter=2147483647 balance=2
network simplex: 4 nodes 4 edges 0 iter 0.00 sec
network simplex:  7 nodes 7 edges maxiter=2147483647 balance=2
network simplex: 7 nodes 7 edges 0 iter 0.00 sec
in label of node X1
Warning: Illegal attribute ALT in <IMG> - ignored

```

Apparently it is using cairo renderer.

Could you please execute the dot command with "-v" option when the links do work in order to compare the output with this one?

**Comment by elysch** [comment] 2024-11-22 01:55
Well there's a difference 

```
}
libgvplugin_pango.so.6 cairo {
        render {
                cairo 10
        }
        textlayout {
                textlayout 10                                      }
        loadimage {
                png:cairo 1
#FAILS          png:lasi 2
                png:ps 2
        }
        device {
                png:cairo 10                                               ps:cairo -10                                               eps:cairo -10                                              pdf:cairo 10                                               svg:cairo -10                                      }                                                  }
libgvplugin_poppler.so.6 poppler {
        loadimage {
                pdf:cairo 1
        }
}                                                          libgvplugin_rsvg.so.6 rsvg {
        loadimage {                                                        svg:cairo 1
        }
}
```

**Comment by Neriderc** [comment] 2024-11-22 05:24
I agree, I don't think png:lasi would be related. So it's probably not the config. Might be the version?

What hardware are you running it on? Is it a SBC (raspberry pi, etc) or some other ARM device, an old desktop/laptop,  or is a commercial VPS?

**Comment by Neriderc** [comment] 2024-11-22 08:15
> Where did you add the needed newline? Downloaded the last main branch and it still shows the marriages one after the other in the same line.

I've just merged the changes into the main branch, so you can check it out now :slightly_smiling_face:. I've also fixed the issue with only one photo showing.

**Comment by elysch** [comment] 2024-11-22 15:31
> I've just merged the changes into the main branch, so you can check it out now 🙂. I've also fixed the issue with only one photo showing.

Thank you very much. I've already tested it. Looks great.


> What hardware are you running it on? Is it a SBC (raspberry pi, etc) or some other ARM device, an old desktop/laptop, or is a commercial VPS?

I have a commercial VPS.

Just for testing I downloaded Graphviz 11 and 12 for windows 11. (No need to install it)

Downloaded a DOT file and converted it to PDF.

Beyond the missing images, with version 11 links didn't work and with the version 12 they did.

I guess some Graphviz versions simply don't handle well the links and others do. Bad luck for me

**Comment by Neriderc** [comment] 2024-11-23 02:49
What's the VPS you're using? Is it ARM or x86? What's the specific OS version you're using? If you let me know the specific company and plan that would help.

If I can recreate your environment I might be able to help find the issue.

**Comment by elysch** [comment] 2024-11-23 16:06
cat /etc/system-release
Rocky Linux release 8.10 (Green Obsidian)
uname -r
4.18.0-553.5.1.el8_10.x86_64

right now I don't remember the company. Sory

**Comment by elysch** [comment] 2024-11-23 23:59
I've just fount the Graphviz [documentation](https://graphviz.org/docs/attrs/URL/) for URL says:

> URL
> Hyperlinks incorporated into device-dependent output
> type: [escString](https://graphviz.org/docs/attr-types/escString/), default: <none>
> 
> At present, used in ps2, cmap, i*map and svg formats. For all these formats, URLs can be attached to nodes, edges and clusters. URL attributes can also be attached to the root graph in ps2, cmap and i*map formats. This serves as the base URL for relative URLs in the former, and as the default image map file in the latter.
> 

It doesn't mention pdf.

**Comment by Neriderc** [comment] 2024-11-24 06:05
> It doesn't mention pdf. Maybe newer versions don't accept links in pdf's

We're actually using the "href" attribute in the HTML-like label, rather than directly on the node. Maybe that makes a difference. 

We just reading this in the [PostScript](https://graphviz.org/docs/outputs/ps/) part:
> Note: The default PostScript renderer can only handle the Latin-1 character set. To get non-Latin-1 characters into PostScript output, use -Tps:cairo, assuming your version was built with the Cairo renderer.

Earlier you mentioned:
> What I've just found is that if I convert .dot to ps and then convert it using ghostscript's ps2pdf , the links do work, but apparently ghostscript doesn't support utf-8

Maybe try using `-Tps:cairo` instead of `-Tps2`?

**Comment by elysch** [comment] 2024-11-24 15:12
Decided to just download the dot file from GVExport and try may windows versions of Graphviz. I placed [this post](https://forum.graphviz.org/t/different-behavior-between-versions-and-links-not-working-in-pdf/2558) asking for help.

Let's see if it shed some light.

**Comment by elysch** [comment] 2024-11-24 19:50
Look. There's an option to [colour the edges](https://forum.graphviz.org/t/too-complex-diagram/1878/2?u=elysch)

**Comment by Neriderc** [comment] 2024-11-24 20:57
> Look. There's an option to [colour the edges](https://forum.graphviz.org/t/too-complex-diagram/1878/2?u=elysch)

If Graphviz, "edges" refers to the lines between the "nodes". In our case, the arrows. 

And we already have options to change the arrow colour. Under Appearance -> Diagram -> Diagram style -> Relationship arrow colour. There is also an option there to use colours based on the relationship (birth or other than birth).

I am realising as I write this that you are probably thinking of the option to use a random style, and perhaps the option to use random colours would be better?

**Comment by elysch** [comment] 2024-11-25 12:51
Hello 

> I am realising as I write this that you are probably thinking of the option to use a random style, and perhaps the option to use random colours would be better?

Yes. Something like that.

I tried this one and liked it.

```
private function getLineColor(): string                    {                                                              static $last = 0;                                          if ($last == 10) {                                             $last = 0;                                             }                                                          $last++;                                                                                                              switch ($last) {
            case 1:
            default:                                                       $color = '#000000';                                        break;                                                 case 2:                                                        $color = '#c0392b';                                        break;
            case 3:
                $color = '#9b59b6';
                break;                                                 case 4:
                $color = '#2980b9';                                        break;                                                 case 5:                                                        $color = '#1abc9c';
                break;                                                 case 6:                                                        $color = '#27ae60';                                        break;
            case 7:
                $color = '#f1c40f';
                break;
            case 8:
                $color = '#e67e22';
                break;
            case 9:
                $color = '#616a6b';
                break;
            case 10:
                $color = '#34495e';
                break;
        }
        return $color;
```

By the way, steveroush made some recommendations about our dot generation. [Here](https://forum.graphviz.org/t/different-behavior-between-versions-and-links-not-working-in-pdf/2558/4)

One of them is about the port names. Now that we have more than one picture, each one should have a different name. Could be pic, picbirth, picdeath, picburial, picmarriage1, picmarriage2, etc

But those changes doesn't seem like would fix my problem though. I'll try

**Comment by elysch** [comment] 2024-11-25 15:03
The width resutls in 0 because is a multiplication and one of the values looks like string:

```
... WIDTH=\"" . ($this->settings["font_size"] * 4 * $photo_size)  . "\" ...
...
'font_size' => '10',    // Default font size for everything except name
'photo_size' => "100%", // Default size of photos

```

**Comment by Neriderc** [comment] 2024-11-26 01:57
> I tried this one and liked it. There is no problem if you like other colors, ofcourse.
> 
> **(The "static" keyword makes the value to be kept between function calls, so it always takes the next color, in the order of the "swtich" structure)**

We don't really know where arrows are heading as we create them, so it may not make a difference deliberately doing one colour after the next or just using a random selection from an array. I'll have a play and see what works well.


> By the way, steveroush made some recommendations about our dot generation. [Here](https://forum.graphviz.org/t/different-behavior-between-versions-and-links-not-working-in-pdf/2558/4)
> 
> One of them is about the port names. Now that we have more than one picture, each one should have a different name. Could be pic, picbirth, picdeath, picburial, picmarriage1, picmarriage2, etc
> 
> But those changes didn't fix my problem though.
> 
> > [quote="steveroush, post:5, topic:2558"]
> > Here are some other suggestions separate from the image problem
> > 
> > * Unless 72 dpi is important to this effort, just use the default of 96 dpi
> > * **mclimit** default is 1. Why explicitly set it to 1?
> > * the documentation says that **pagedir** is ignored unless **page** is set.
> > * the **port** names all see to be _pic_. For a given node, the port names must be unique.
> > * some of the cells have **width=“0”**. Though undocumented, a positive integer seems to be required.
> >   [/quote]

These are things that can be solved easily enough, but it would be good to first work out why your links don't work! Try making the changes manually and see if it fixes them. You could also try using a label attribute on a basic shape instead of our complicated HTML-like labels, and see if they work using that approach (we probably can't actually fix things like that, but it would be good to know if it does help).

**Comment by elysch** [comment] 2024-11-26 02:17
Thank you very much for the patience and effort.

Just those changes didn't fix anything.

I'll try your other suggestions and let you know.

**Comment by elysch** [comment] 2024-11-27 21:55
Just to let you know that [steveroush](https://forum.graphviz.org/u/steveroush) suggested to open an issue, and there [Matthew Fernandez](https://gitlab.com/smattr)
 said "I think to troubleshoot this we’re going to need the referenced images."

I tried it removing the images from the .dot file and this time generated a pdf file with links working and all. Let's see what happens with the issue.

**Comment by Neriderc** [comment] 2024-11-28 01:07
That's a big clue! Does it work generating from GVExport with all photo settings disabled?

**Comment by elysch** [comment] 2024-11-28 13:26
Good question. 

No, it still doesn't have links.  :'(

**Comment by Neriderc** [comment] 2024-12-02 05:37
Hmm. it does seem to be related to the specific version then. If you manage to find and changes that allow it to work in the older version, please let me know! I'm happy to make changes if you work out what the issue is.

**Comment by elysch** [comment] 2024-12-02 23:09
Maybe if we could remove the EXIF information on the JPG files could work... but then, I don't know if it's enough.

**Comment by Neriderc** [comment] 2024-12-03 08:33
I just had a read through [the issue you filed](https://gitlab.com/graphviz/graphviz/-/issues/2619).

It seems like there might be two issues. The later version installed on windows seems to have issues with the specific images you have, but it seems that this must be unrelated to your original issue. If you switch off images in GVExport and the links still don't work (in your Rocky Linux environment with Graphviz 2.44), then it must not be related to the images like you're seeing with Graphviz 12.

I don't think I can help much at the moment, I'll let your issue play out and see if you get a resolution from it.

**Closed** 2024-12-11 06:13 UTC
Labels: pre-release bug

**Comment by elysch** [comment] 2024-12-11 19:15
As a final note, I discovered I can generate (download) the report in SVG format, and then convert it to pdf using an [online service](https://tools.pdf24.org/es/convertir-a-pdf). This way, the links and images do work ok in the final PDF file.

BE AWARE: I don't know what does that service does with the uploaded files, I mean, I don't know if they gather it's contents for other uses (licit or illicit).
