### ISSUE TITLE
Tile colour

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#397] opened 2023-03-19 13:40 UTC
The tile background/stripe/border colour is depending at the moment on

- sex of individual
- blood-relationsship
- start individual

There was a discussion some time ago in the webtrees forum https://www.webtrees.net/index.php/en/forum/4-customising/36811-individual-color#91283 about tile colours. Some ideas how to use the tile background/stripe/border colour are
- show death/alive
- show age (dark colour = died at high age, light = died as child)
- use a special colour for an individual based on new custom GEDCOM tag INDI:_CHART_COLOR <color_code>

The last option would allow you to tag individuals with a special color. This can be used to indicate all persons in a tree that died with a genetical illness. Or to mark all persons in "succession to the throne". Or to indicate persons with a special occupation (for example in my family there are many organ builders and it would be nice to show them in the family tree).

At the moment background/stripe/border are mixed together in GVExport. So I suggest to seperate those three elements (btw: there are two words used for the same thing: "border" and "outline" ) and allow the user to select what is used for what. For example use the background for blood-relationship, the stripe for sex, and the border for alive/dead. Or use the background for sex, the stripe for alive/dead, and the border for blood-relationsship. I think this gives more flexibility and allows to group the options better (unbundling).

**Comment by hartenthaler** [comment] 2023-03-19 13:48
Maybe there are even more options
- use the tile shape for sex (sharp = male, rounded = female)
- add an icon
  - a mourning ribbon to indicate dead individuals
  - a crown as a symbol for persons with a noble title
  - colorful balloons when a birthday/wedding anniversary is coming up

**Comment by schuco** [comment] 2023-03-19 17:26
Good ideas!
Some of these are already implemented inGVE as mentioned by @hartenthaler.
In addition we can even select which of the starting persons to be higlighted.

One question is if selection for special tagging of individuals should be done
-  more permantly like with new custom GEDCOM or
- just temporarily by options for a GVE graph.

For the latter case we might extend the new search function with the ability to add "decorative" options for the selected individuals

**Comment by Neriderc** [comment] 2023-03-19 23:35
Thanks for raising this, there are some great ideas here. 

> At the moment background/stripe/border are mixed together in GVExport. So I suggest to seperate those three element

This is a good point. Currently we have a setting that sets e.g. how to show the sex of the individual. But you could show this in multiple ways (background colour and border), while the background colour can only be set to one thing. Therefore, as you suggest, we should have an option for how to set the background colour which lists "sex" as an option, not an option for sex that sets "background colour" as an option.

This then makes it easier to implement these new ideas. I would say that #396 should be completed first (including this restructure of tile setttings), then we can look at adding new options such as these.

**Comment by Neriderc** [comment] 2023-05-13 02:15
Ok so the refactor is done, so now I'm looking at this, and it's raising more questions.

As I understand it, we have a proposal for the following:

1. Background/stripe/border colour based on dead/alive
2. Background/stripe/border colour based on age of individual
3. Background/stripe/border colour based on a custom GEDCOM tag
4. Tile shape based on sex
5. The ability to add icons in certain situations

I have questions about most of these:

1. I think this one is pretty straightforward. Allow setting two different colours for dead/alive and use webtrees isDead function to determine if individual is dead (so setting for treating individuals over a certain age as dead is followed)
2. Is this a gradient? So if you pick dark green for young and white for old, then a teenager person would have a slightly lighter dark green and a 90-year-old would have an almost white but still slightly green colour? Does a 0-100 scale work for this, where 0 is (say) green, 100 is white, and anything over 100 is white as well?
3. How do you add custom tags in webtrees?
4. This is a good idea, but the problem is we have two tile shapes but webtrees has 4 sex options. What would we do with other and unknown?
5. Would these be all in the same place (say in a corner or by their name), or would e.g. the mourning ribbon be next to the date of death, balloons next to their date of birth/marriage, etc? Presumably you would be able to enable multiple, so we would need a selection for each of the different options where the user could enable/disable it, and possibly also change the icon.

**Comment by hartenthaler** [comment] 2023-05-13 15:26
1. ok
2. Yes, it could be a gradient. Yes, I would use the age-at-death range from 0 to 100 years (or older). And a colour range from dark green (died at 100) to light green (stillborn). Or a range from green (died at 100) to red (stillborn). And if birth or death date are unknown: grey.
3. It is possible to use custom tags in webtrees without any problems. But if you like to support them in editing masks and check the allowed values of such a tag, you need to add the tag in a custom module. So finally I think it is not a good idea to use custom GEDCOM tags. It would be better to use a shared note. For example, use a shared note "Custom colour: succession to the throne" or "Custom colour: genetic problem BRCA1". You can use the build-in functions of webtrees to manage such shared notes. There should be a management function in GVExport with a list to map such shared notes to a tile background/border colour or an icon.
4. Use sharp = male, rounded = female and let the user decide if unknown/other = sharp or rounded, too.
5. I would prefer
- left-top-corner: mourning ribbon
- ballons/birthday cake behind the tile right-top-corner
- maybe other coloured markers inside the tile on the right side

Examples from MyHeritage:
![Screenshot (296) - Kopie](https://github.com/Neriderc/GVExport/assets/6324175/5c096aa9-c0b3-4bcf-9453-5b70870ead60)
![Screenshot (297)](https://github.com/Neriderc/GVExport/assets/6324175/8b2bcbdc-f739-4a2a-80b4-4a1ce9b3093d)
![Screenshot (296)](https://github.com/Neriderc/GVExport/assets/6324175/ac708613-d7db-42ad-8cc6-03125dc211fb)

**Comment by Neriderc** [comment] 2023-05-14 03:30
Ok, thanks. I will split these each out into their own issues as there is quite a bit in here. Then I'll start to tackle them one by one, starting with the easiest :)

**Comment by Neriderc** [comment] 2023-05-15 00:09
Closing as we now have separate issues for each of the parts.

**Closed by Neriderc** 2023-05-15 00:09 UTC
Labels: enhancement
