### ISSUE TITLE
GVE box not opening on Android device

### ISSUE THREAD

**Issue by schuco** [Neriderc/GVExport#219] opened 2022-09-24 09:23 UTC
I already have noticed that displayed persons are not "clickable" using GVE under Android. However the diagram was displayed and could be zoomed more or less satisfactory.
With the actual version 2.1.11 there is only a small rectangle displayed which can not be zoomed and no content is visible.
The non-clickable behaviour may be due to an incomplete javascript under Android.
The nonzooming box may have come after Panzoom was included into GVE and may be another deficiency of the Android implementation of javascript.

I am using Android 12 on a Samsung S7FE tablet and S20FE smartphone.

**Comment by Neriderc** [comment] 2022-09-24 10:03
I have generally found that GVExport has worked poorly on my mobile. I can imagine it's better on a tablet, but the settings panel is a fixed size so if your screen can't fit it, you just can't hide it to see the diagram behind it. I have known of this poor design but made no efforts to improve it. Instead I select desktop mode in my mobile browser and it works fine for me.

For your issue, I suspect this would not fix it. I am using Firefox for Android on my Samsung S10+ and the diagram loads and can be scrolled and zoomed with version 2.1.11. I have also tested on Chrome. Unfortunately it's a lot harder to resolve issues on mobile because the browsers don't have debugging tools, though there are ways to connect to them. The first step to resolving this would need to be that I can reproduce this issue. What browser are you using?

**Comment by schuco** [comment] 2022-09-24 10:23
It works with the desktop-website.
But not with mobile mode. I am using Firefox under Android 12.
I described the problem a bit incorrectly. You can see some content of the diagram. But the box is very small and can't be zoomed.

**Comment by Neriderc** [comment] 2022-09-24 10:57
> It works with the desktop-website. But not with mobile mode. 

Just to confirm, it works if you select desktop mode in your mobile browser (both phone and tablet), but not if desktop mode is disabled?

> I am using Firefox under Android 12. I described the problem a bit incorrectly. You can see some content of the diagram. But the box is very small and can't be zoomed.

I am also using Firefox under Android 12. I can drag to move the diagram, and do a pinch action to zoom out (and the reverse to zoom in). Some components of the webtrees UI are a fixed size, but the diagram box is auto-sized to the screen. This could be a cause of a very small box. If the box is too small, it probably wouldn't respond to actions to zoom as it wouldn't have space for the pinch action. 

It makes sense for the box to have a minimum size. I have made a small change to set a minimum height, which in my experience is the main issue. Could you download the main branch code and test that? (go to [main repo page](https://github.com/Neriderc/GVExport), click green "Code" button, then "Download ZIP", and install as normal).

If this doesn't help, is it possible to get a screen shot of how it looks? I'm particularly interested in how the very small box looks.

**Comment by schuco** [comment] 2022-09-24 12:22
Presently I am away from home and don't have access to the server. I will test your change coming home.
Meanwhile I send a screenshot from my mobile Firefox browser with desktop-mode disabled:
![Screenshot_20220924_140615_Firefox](https://user-images.githubusercontent.com/5896925/192097163-54982876-2a84-426c-82e8-40c13c2e0a76.jpg)
Following your description I was able to do some zooming in this small box. But the visible part was very limited compared to the desktop mode.
I did not know about the advantage to use desktop mode in this case before  and I now have learned that mobile browsers need stronger restrictions in the display of  diagrams. 
So don't put to much effort on this issue.

**Comment by Neriderc** [comment] 2022-09-24 18:18
Thanks for that! I strongly suspect my little change will resolve this for you. Once you get a chance please let me know how it goes :)

**Comment by schuco** [comment] 2022-09-28 19:04
Back home I tried the main branch and your change works as good as in desktop mode. Thank you!!!

Playing around a bit with my Android tablet I saw, the switching to other fonts, this did not work properly. Choosing Times New Roman seems to result in displaying Arial as before but the spacing of the name was disturbed.

**Comment by Neriderc** [comment] 2022-09-29 03:38
GVExport doesn't provide the font, but it requests the font from the system. A quick search and it seems Times New Roman is not installed (by default) on Android devices. It seems the "web safe" fonts are not so safe after all.

If you have GraphViz installed on your server, and select to download a file instead of rendering in the browser, then it should show Times New Roman in the output (presuming it's installed on the server, which it most likely is). This is because GraphViz runs on the server so will use the fonts from the server.

Currently Arial is listed as the fallback font, which is why you see Arial instead. In fact it is probably Droid Sans, which is a Sans-serif font so may look similar to Arial. Perhaps for Serif fonts like Times New Roman we should have the fallback as the default Serif font. That way if Times New Roman is not available, you'll still get a somewhat similar font. Android appears to only have three fonts by default. A Sans-serif font, an Serif font, and a monospace font. None of these are on our list, but by setting appropriate fallbacks we may be able to leverage these (i.e. if you select Times New Roman, you'll get the serif font when on Android.

An alternate option is to distribute fonts ourselves with the package. But I think we wouldn't be able to distribute the listed fonts because they are not open source licenced, so we would have to choose new unfamiliar fonts.

I don't believe there is a way to list fonts available. This would probably be a privacy nightmare because it would be relatively unique between devices (if you want to learn more then you can[ read this on wikipedia,](https://en.wikipedia.org/wiki/Device_fingerprint) though it really only covers the "what" and not the "why").

All in all I think changing the fallback fonts to be different for each font is probably the best option for this.

**Comment by schuco** [comment] 2022-09-29 16:42
It would be quite time-consuming to improve and perfect GVE not only for Windows but also for Android and maybe  Apple-devices.
In my opinion it would be sufficient that you just can display diagrams with the browser on Android or Apple tablet. But you can do without using special fonts. 
I would propose not to spent too much effort to bring GVE to perfection for these platforms and just declare that there are known deficiencies especially non clickable names and also no alternative fonts. So to get perfect diagrams using mobile devices one should download from GraphViz.

**Comment by Neriderc** [comment] 2022-09-30 08:51
Yes I agree it probably does not make sense to invest too much effort into this at this time, but the fallback fonts should be of the same family and that's not a difficult thing to do so I'd like to make that change.

We still have a fair number of enhancements to do but I would at some point like to make GVE more mobile friendly. Being able to bring up GVE on your phone to show others would be a nice thing to be able to do.

**Closed** 2022-10-04 09:31 UTC

**Comment by Neriderc** [comment] 2022-10-04 09:42
I have made this change, introducing separate fallback generic font families for each font in the list (e.g. Times New Roman has the fallback generic font family "Sans"). This will be in the next release.
