### ISSUE TITLE
When saving/loading settings the diagram type is not restored successfully

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#335] opened 2023-02-02 06:20 UTC
![Screenshot (166)](https://user-images.githubusercontent.com/6324175/216246741-f363dea0-4b76-4e61-a3ec-b73c14859a47.png)

As you can see in the screenshot it could happen that the diagram type (simple/decorated/combined) is not restored correctly when loading a settings from the stored settings. It can happen that no diagram type is selected at all.

**Comment by Neriderc** [comment] 2023-02-02 06:40
Do you have a repeatable set of steps that cause this to happen?

At least for me, it sets the setting correctly when I test it. It would be good if there is a set of steps that cause it so I can try to fix it.

**Comment by hartenthaler** [comment] 2023-02-03 04:44
I don't know if it helps:

- I generated two settings: test2 and test3 (I can't remember exactly what I have done to generate them)
- if I load test2 first: http://ahnentest.hartenthaler.eu/index.php?route=%2Fmodule%2F_GVExport_%2FChart%2Ftree1&t=QM3EGA23S8
- and then load test3: http://ahnentest.hartenthaler.eu/index.php?route=%2Fmodule%2F_GVExport_%2FChart%2Ftree1&t=6CR1VZ1835

Then the diagram type is not set.

**Comment by Neriderc** [comment] 2023-02-03 06:16
Yes that's great, thanks! I don't know when I'll get a chance to take a look, it might be a few days, but I'll take a look when I can.

**Comment by hartenthaler** [comment] 2023-02-03 07:38
I'm happy that this new function to share links to settings helps in debugging the function to share links. It wakes up some very old memories about how to build up a compiler that compiles itself.

**Comment by Neriderc** [comment] 2023-02-07 10:13
I don't yet have a fix for this, but it seems loading the value of check boxes and radio buttons is not working great. This is something I have struggled with quite a bit. True/False values are stored differently in JavaScript and PHP when converted to JSON, with signed out users having setting saved in local storage with JavaScript, and signed in users having settings saved on the server via PHP. I tried to standardise this, but it has caused more issues.

I think this is the root of the problem. I can the JSON coming from the server with your links by looking at the network requests, and this appears fine. I'm sure it's loading this with JavaScript that is the problem. I will do some more playing and see if I can't find a consistent way to reproduce it.

Do you see the same issue with check boxes? You've said if you load test2 first, then load test3, it causes the issue. If you also uncheck a few boxes in between, do you find these aren't loaded?

I am seeing issues myself, so will have to try again to solve this issue.

**Closed** 2023-02-08 08:53 UTC
Labels: pre-release bug

**Comment by Neriderc** [comment] 2023-02-08 08:59
I managed to find a set of steps to reproduce something similar to this.
1. Log in
2. Clear all settings
3. Add setting (check all checkboxes, set diagram type to say Simple)
4. Add another setting (uncheck checkboxes, set diagram type to say Decorated - just different from first so we can tell if it's working)
5. DON'T reload page, just try to load each setting.

This didn't properly load. Refreshing the page resolves the issue, and from that point they work fine.

I've made some changes to how the check boxes are set, and I can't reproduce it anymore.

Could you test to make sure this is resolved?

**Comment by hartenthaler** [comment] 2023-02-08 14:14
Tested! And the error does not appear any more. Great!
